# coding: utf-8

"""
    Gavagai Explorer API

    <p>This is the technical documentation for the Gavagai Explorer API.</p><p>We recommend that you get familiar with using <a href=\"https://explorer.gavagai.se/\">Gavagai Explorer</a> before you start developing with the API. The Explorer has its own <a href=\"https://gavagai-corp.github.io/explorer/\"> general documentation</a>.</p><p>Make sure that you understand the basic procedures, such as creating projects and uploading texts, exploring and refining your project, or creating reports and applying models. All functionality in Gavagai Explorer is built on this API, so you will have a much easier time understanding the different steps if you have already seen them in the Explorer web interface.</p> <p>The <a href=\"https://gavagai.atlassian.net/wiki/spaces/PUB/pages/99319872/Gavagai+Explorer+API+Tutorial\">Getting Started</a> tutorial and the <a href=\"https://gavagai.atlassian.net/wiki/spaces/PUB/pages/322797577/Explorer+API+Common+Use+Cases\"> Common Use Cases </a>section provide more guidance in understanding how the different API calls can be fitted together to create a workflow. The documentation below then provides full technical specifics for each endpoint.</p>  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from explorer_client.configuration import Configuration


class ManagerInvitation(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'recipient': 'User',
        'sender': 'User',
        'created': 'int'
    }

    attribute_map = {
        'id': 'id',
        'recipient': 'recipient',
        'sender': 'sender',
        'created': 'created'
    }

    def __init__(self, id=None, recipient=None, sender=None, created=None, local_vars_configuration=None):  # noqa: E501
        """ManagerInvitation - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._recipient = None
        self._sender = None
        self._created = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if recipient is not None:
            self.recipient = recipient
        if sender is not None:
            self.sender = sender
        if created is not None:
            self.created = created

    @property
    def id(self):
        """Gets the id of this ManagerInvitation.  # noqa: E501


        :return: The id of this ManagerInvitation.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ManagerInvitation.


        :param id: The id of this ManagerInvitation.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def recipient(self):
        """Gets the recipient of this ManagerInvitation.  # noqa: E501


        :return: The recipient of this ManagerInvitation.  # noqa: E501
        :rtype: User
        """
        return self._recipient

    @recipient.setter
    def recipient(self, recipient):
        """Sets the recipient of this ManagerInvitation.


        :param recipient: The recipient of this ManagerInvitation.  # noqa: E501
        :type recipient: User
        """

        self._recipient = recipient

    @property
    def sender(self):
        """Gets the sender of this ManagerInvitation.  # noqa: E501


        :return: The sender of this ManagerInvitation.  # noqa: E501
        :rtype: User
        """
        return self._sender

    @sender.setter
    def sender(self, sender):
        """Sets the sender of this ManagerInvitation.


        :param sender: The sender of this ManagerInvitation.  # noqa: E501
        :type sender: User
        """

        self._sender = sender

    @property
    def created(self):
        """Gets the created of this ManagerInvitation.  # noqa: E501


        :return: The created of this ManagerInvitation.  # noqa: E501
        :rtype: int
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this ManagerInvitation.


        :param created: The created of this ManagerInvitation.  # noqa: E501
        :type created: int
        """

        self._created = created

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ManagerInvitation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ManagerInvitation):
            return True

        return self.to_dict() != other.to_dict()
