# coding: utf-8

"""
    Gavagai Explorer API

    <p>This is the technical documentation for the Gavagai Explorer API.</p><p>We recommend that you get familiar with using <a href=\"https://explorer.gavagai.se/\">Gavagai Explorer</a> before you start developing with the API. The Explorer has its own <a href=\"https://gavagai-corp.github.io/explorer/\"> general documentation</a>.</p><p>Make sure that you understand the basic procedures, such as creating projects and uploading texts, exploring and refining your project, or creating reports and applying models. All functionality in Gavagai Explorer is built on this API, so you will have a much easier time understanding the different steps if you have already seen them in the Explorer web interface.</p> <p>The <a href=\"https://gavagai.atlassian.net/wiki/spaces/PUB/pages/99319872/Gavagai+Explorer+API+Tutorial\">Getting Started</a> tutorial and the <a href=\"https://gavagai.atlassian.net/wiki/spaces/PUB/pages/322797577/Explorer+API+Common+Use+Cases\"> Common Use Cases </a>section provide more guidance in understanding how the different API calls can be fitted together to create a workflow. The documentation below then provides full technical specifics for each endpoint.</p><p>Use <code>https://api.gavagai.se/explorer/v1/</code> as the Base URL for each of these API endpoints</p>  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from explorer_client.configuration import Configuration


class NgramScore(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'score': 'float',
        'ngram': 'str',
        'keyword': 'bool',
        'negation': 'bool',
        'amplifier': 'bool'
    }

    attribute_map = {
        'score': 'score',
        'ngram': 'ngram',
        'keyword': 'keyword',
        'negation': 'negation',
        'amplifier': 'amplifier'
    }

    def __init__(self, score=None, ngram=None, keyword=None, negation=None, amplifier=None, local_vars_configuration=None):  # noqa: E501
        """NgramScore - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._score = None
        self._ngram = None
        self._keyword = None
        self._negation = None
        self._amplifier = None
        self.discriminator = None

        if score is not None:
            self.score = score
        if ngram is not None:
            self.ngram = ngram
        if keyword is not None:
            self.keyword = keyword
        if negation is not None:
            self.negation = negation
        if amplifier is not None:
            self.amplifier = amplifier

    @property
    def score(self):
        """Gets the score of this NgramScore.  # noqa: E501


        :return: The score of this NgramScore.  # noqa: E501
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this NgramScore.


        :param score: The score of this NgramScore.  # noqa: E501
        :type score: float
        """

        self._score = score

    @property
    def ngram(self):
        """Gets the ngram of this NgramScore.  # noqa: E501


        :return: The ngram of this NgramScore.  # noqa: E501
        :rtype: str
        """
        return self._ngram

    @ngram.setter
    def ngram(self, ngram):
        """Sets the ngram of this NgramScore.


        :param ngram: The ngram of this NgramScore.  # noqa: E501
        :type ngram: str
        """

        self._ngram = ngram

    @property
    def keyword(self):
        """Gets the keyword of this NgramScore.  # noqa: E501


        :return: The keyword of this NgramScore.  # noqa: E501
        :rtype: bool
        """
        return self._keyword

    @keyword.setter
    def keyword(self, keyword):
        """Sets the keyword of this NgramScore.


        :param keyword: The keyword of this NgramScore.  # noqa: E501
        :type keyword: bool
        """

        self._keyword = keyword

    @property
    def negation(self):
        """Gets the negation of this NgramScore.  # noqa: E501


        :return: The negation of this NgramScore.  # noqa: E501
        :rtype: bool
        """
        return self._negation

    @negation.setter
    def negation(self, negation):
        """Sets the negation of this NgramScore.


        :param negation: The negation of this NgramScore.  # noqa: E501
        :type negation: bool
        """

        self._negation = negation

    @property
    def amplifier(self):
        """Gets the amplifier of this NgramScore.  # noqa: E501


        :return: The amplifier of this NgramScore.  # noqa: E501
        :rtype: bool
        """
        return self._amplifier

    @amplifier.setter
    def amplifier(self, amplifier):
        """Sets the amplifier of this NgramScore.


        :param amplifier: The amplifier of this NgramScore.  # noqa: E501
        :type amplifier: bool
        """

        self._amplifier = amplifier

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NgramScore):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NgramScore):
            return True

        return self.to_dict() != other.to_dict()
