# coding: utf-8

"""
    Gavagai Explorer API

    <p>This is the technical documentation for the Gavagai Explorer API.</p><p>We recommend that you get familiar with using <a href=\"https://explorer.gavagai.se/\">Gavagai Explorer</a> before you start developing with the API. The Explorer has its own <a href=\"https://gavagai-corp.github.io/explorer/\"> general documentation</a>.</p><p>Make sure that you understand the basic procedures, such as creating projects and uploading texts, exploring and refining your project, or creating reports and applying models. All functionality in Gavagai Explorer is built on this API, so you will have a much easier time understanding the different steps if you have already seen them in the Explorer web interface.</p> <p>The <a href=\"https://gavagai.atlassian.net/wiki/spaces/PUB/pages/99319872/Gavagai+Explorer+API+Tutorial\">Getting Started</a> tutorial and the <a href=\"https://gavagai.atlassian.net/wiki/spaces/PUB/pages/322797577/Explorer+API+Common+Use+Cases\"> Common Use Cases </a>section provide more guidance in understanding how the different API calls can be fitted together to create a workflow. The documentation below then provides full technical specifics for each endpoint.</p><p>Use <code>https://api.gavagai.se/explorer/v1/</code> as the Base URL for each of these API endpoints</p>  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from explorer_client.configuration import Configuration


class ProjectVersionsChangeSet(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'version': 'int',
        'comparing_version': 'int',
        'model_change_set': 'ModelChangeSet'
    }

    attribute_map = {
        'version': 'version',
        'comparing_version': 'comparingVersion',
        'model_change_set': 'modelChangeSet'
    }

    def __init__(self, version=None, comparing_version=None, model_change_set=None, local_vars_configuration=None):  # noqa: E501
        """ProjectVersionsChangeSet - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._version = None
        self._comparing_version = None
        self._model_change_set = None
        self.discriminator = None

        if version is not None:
            self.version = version
        if comparing_version is not None:
            self.comparing_version = comparing_version
        if model_change_set is not None:
            self.model_change_set = model_change_set

    @property
    def version(self):
        """Gets the version of this ProjectVersionsChangeSet.  # noqa: E501


        :return: The version of this ProjectVersionsChangeSet.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ProjectVersionsChangeSet.


        :param version: The version of this ProjectVersionsChangeSet.  # noqa: E501
        :type version: int
        """

        self._version = version

    @property
    def comparing_version(self):
        """Gets the comparing_version of this ProjectVersionsChangeSet.  # noqa: E501


        :return: The comparing_version of this ProjectVersionsChangeSet.  # noqa: E501
        :rtype: int
        """
        return self._comparing_version

    @comparing_version.setter
    def comparing_version(self, comparing_version):
        """Sets the comparing_version of this ProjectVersionsChangeSet.


        :param comparing_version: The comparing_version of this ProjectVersionsChangeSet.  # noqa: E501
        :type comparing_version: int
        """

        self._comparing_version = comparing_version

    @property
    def model_change_set(self):
        """Gets the model_change_set of this ProjectVersionsChangeSet.  # noqa: E501


        :return: The model_change_set of this ProjectVersionsChangeSet.  # noqa: E501
        :rtype: ModelChangeSet
        """
        return self._model_change_set

    @model_change_set.setter
    def model_change_set(self, model_change_set):
        """Sets the model_change_set of this ProjectVersionsChangeSet.


        :param model_change_set: The model_change_set of this ProjectVersionsChangeSet.  # noqa: E501
        :type model_change_set: ModelChangeSet
        """

        self._model_change_set = model_change_set

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectVersionsChangeSet):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectVersionsChangeSet):
            return True

        return self.to_dict() != other.to_dict()
